version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - ../.env
    depends_on:
      - db
      - redis
    volumes:
      - ../backend:/app

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ../.env
    volumes:
      - ../frontend:/app
      - /app/node_modules

  db:
    image: postgres:15
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery:
    build:
      context: ../worker
      dockerfile: Dockerfile
    env_file:
      - ../.env
    depends_on:
      - redis
    volumes:
      - ../worker:/app
    ports:
      - "5556:5556"

  avatar-service:
    build:
      context: ../avatar-service
      dockerfile: Dockerfile
    env_file:
      - ../.env
    volumes:
      - ../avatar-service:/app
    ports:
      - "5002:5002"

volumes:
  postgres_data: